language: python
install:
  - pip install tox
script:
  - tox
env:
  - TOXENV=py26-dj14
  - TOXENV=py27-dj14
  - TOXENV=py26-dj15
  - TOXENV=py26-dj16
  - TOXENV=py27-dj15
  - TOXENV=py27-dj16
  - TOXENV=py27-dj17
  - TOXENV=py34-dj15
  - TOXENV=py34-dj16
  - TOXENV=py34-dj17
  - TOXENV=pep8
  - TOXENV=coverage

